name: build

on: [workflow_dispatch, push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Install flatc
        uses: Nugine/setup-flatc@v1
      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip git wget
          python sys/tools/setup_libcxx_prepackaged.py
          python sys/tools/setup_sail.py
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
          sudo apt-get install -y clang-20 llvm-20 lld-20
          sudo ln -sf /usr/bin/clang-20 /usr/bin/clang
          sudo ln -sf /usr/bin/clang++-20 /usr/bin/clang++
          python3 -m pip install pyelftools mmh lz4
          mkdir -p $HOME/.local/bin
          curl -sSL https://github.com/lincoln-lm/ultimate_tex/releases/download/release/ultimate_tex_cli_linux_x64.zip | funzip > $HOME/.local/bin/ultimate_tex_cli
          chmod +x $HOME/.local/bin/ultimate_tex_cli
          curl -sSL https://github.com/lincoln-lm/BntxFixer/releases/download/release/BntxFixer -o $HOME/.local/bin/BntxFixer
          chmod +x $HOME/.local/bin/BntxFixer
          curl -sSL https://github.com/lincoln-lm/ShaderLibrary/releases/download/release/ShaderLibrary.CompileTool -o $HOME/.local/bin/ShaderLibrary.CompileTool
          chmod +x $HOME/.local/bin/ShaderLibrary.CompileTool
          curl -sSL https://github.com/lincoln-lm/EffectLibrary/releases/download/release/EffectShaderReplacer -o $HOME/.local/bin/EffectShaderReplacer
          chmod +x $HOME/.local/bin/EffectShaderReplacer
          curl -sSL https://github.com/lincoln-lm/uam/releases/download/release/uam -o $HOME/.local/bin/uam-nvn
          chmod +x $HOME/.local/bin/uam-nvn
      - name: Build RomFS
        run: |
          pip install uv
          cd romfs
          uv run generate_romfs.py
          cd ..
      - name: Build Sword
        env:
          TITLE_ID: '0x0100ABF008968000'
        run: |
          rm -rf build
          cmake -B build -DCMAKE_BUILD_TYPE="Debug"
          cmake --build build -j $(nproc)
      - name: Build Shield
        env:
          TITLE_ID: '0x01008DB008C2C000'
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE="Debug"
          cmake --build build -j $(nproc)
      - name: Copy RomFS
        run: |
          cp -r romfs/build build/sd/atmosphere/contents/0100ABF008968000/romfs
          cp -r romfs/build build/sd/atmosphere/contents/01008DB008C2C000/romfs
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mod
          path: |
            build/sd
            third-party-licenses
            LICENSE